// Your plan as exported from the Claude version. Loaded into storage on first run.
export default {
 "items/b01": {
  "cat": "flights",
  "cost": 22000,
  "cur": "JPY",
  "detail": "Your receipt shows only 8 kg carry-on each for the flight home. Add bags in Manage Booking at zipair.net: ¥11,000 per piece, more at the airport counter.",
  "done": false,
  "group": "b-now",
  "links": [
   {
    "label": "ZIPAIR: manage booking",
    "url": "https://www.zipair.net/"
   }
  ],
  "paid": false,
  "priority": "low",
  "sort": 10,
  "time": "",
  "title": "Buy return checked bags on ZG024",
  "updatedAt": 1790749112810,
  "updatedBy": "u_lLV6xNmVXtmEjgJs9XlOBg"
 },
 "items/b02": {
  "detail": "Only 22 rooms, and it's cherry season.",
  "done": false,
  "group": "b-now",
  "links": [
   {
    "label": "Matsuzakaya Honten",
    "url": "https://kinnotake-resorts.com/matsuzakayahonten/en/access"
   }
  ],
  "priority": "high",
  "sort": 20,
  "time": "",
  "title": "Matsuzakaya Honten, Apr 4–6"
 },
 "items/b03": {
  "detail": "1 night, $680.",
  "done": false,
  "group": "b-now",
  "links": [
   {
    "label": "Cerulean Tower",
    "url": "https://tokyuhotels.co.jp/en/cerulean-h/access/index.html"
   }
  ],
  "priority": "high",
  "sort": 30,
  "time": "",
  "title": "Cerulean Tower, Apr 1"
 },
 "items/b04": {
  "detail": "Or Hotel Koé.",
  "done": false,
  "group": "b-now",
  "links": [
   {
    "label": "Trunk (Hotel)",
    "url": "https://trunk-hotel.com"
   }
  ],
  "priority": "high",
  "sort": 40,
  "time": "",
  "title": "Trunk (Hotel), Apr 2–4"
 },
 "items/b05": {
  "detail": "Ryokan Gion Sano (value) or Yuzuya (splurge).",
  "done": false,
  "group": "b-now",
  "links": [
   {
    "label": "Gion Sano",
    "url": "https://www.insidekyoto.com/kyoto-ryokan-gion-sano"
   },
   {
    "label": "Yuzuya",
    "url": "https://booking.com/hotel/jp/yuzuya-ryokan.html"
   }
  ],
  "priority": "high",
  "sort": 50,
  "time": "",
  "title": "Kyoto ryokan, Apr 6–10"
 },
 "items/b06": {
  "detail": "Naoshima Ryokan Roka or Benesse House. Benesse changed its booking system for stays from August 2026.",
  "done": false,
  "group": "b-now",
  "links": [
   {
    "label": "Naoshima Ryokan Roka",
    "url": "https://roka.voyage/en/"
   }
  ],
  "priority": "high",
  "sort": 60,
  "time": "",
  "title": "Naoshima stay, Apr 10–12"
 },
 "items/b07": {
  "detail": "Ryokan Sawanoya (Yanaka) or Nui. Hostel & Bar Lounge (Kuramae).",
  "done": false,
  "group": "b-now",
  "links": [
   {
    "label": "Ryokan Sawanoya",
    "url": "http://www.sawanoya.com/"
   }
  ],
  "priority": "medium",
  "sort": 70,
  "time": "",
  "title": "East Tokyo stay, Apr 12–14"
 },
 "items/b08": {
  "detail": "First entry slot.",
  "done": false,
  "group": "b-march",
  "links": [
   {
    "label": "teamLab tickets",
    "url": "https://www.teamlab.art/e/tokyo/"
   }
  ],
  "priority": "medium",
  "sort": 10,
  "time": "",
  "title": "teamLab Borderless, Sat Apr 3"
 },
 "items/b09": {
  "detail": "Shinjuku → Hakone-Yumoto, 11:00 AM or close. Seats open at 10:00 AM Japan time one month ahead (Mar 4).",
  "done": false,
  "group": "b-march",
  "links": [
   {
    "label": "e-Romancecar",
    "url": "https://www.odakyu.jp/english/?p=4039"
   }
  ],
  "priority": "medium",
  "sort": 20,
  "time": "",
  "title": "Romancecar seats, Sun Apr 4"
 },
 "items/b10": {
  "detail": "Optional.",
  "done": false,
  "group": "b-march",
  "priority": "low",
  "sort": 30,
  "time": "",
  "title": "Farewell kaiseki in Kyoto, Fri Apr 9"
 },
 "items/b11": {
  "detail": "Sales open Feb 5, 10:00 AM Japan time. No changes or refunds; the slot is void if you're 30+ minutes late.",
  "done": false,
  "group": "b-feb",
  "links": [
   {
    "label": "Chichu tickets",
    "url": "https://www.e-tix.jp/chichu/en/"
   }
  ],
  "priority": "high",
  "sort": 10,
  "time": "",
  "title": "Chichu Art Museum, Sat Apr 10, about 2 PM"
 },
 "items/b12": {
  "detail": "Minamidera around 10:15 AM; Teshima Art Museum around 2:00 PM. Timed tickets on the Benesse Art Site page.",
  "done": false,
  "group": "b-feb",
  "links": [
   {
    "label": "Benesse Art Site tickets",
    "url": "https://benesse-artsite.jp/en/general-information.html"
   }
  ],
  "priority": "high",
  "sort": 20,
  "time": "",
  "title": "Teshima Art Museum and Minamidera, Sun Apr 11"
 },
 "items/b13": {
  "detail": "Reserve the 4:20 PM bus (arrives 6:05). Only a few buses run each afternoon; the next is 5:50 PM.",
  "done": false,
  "group": "b-fly",
  "links": [
   {
    "label": "Reserve the bus",
    "url": "https://www.limousinebus.co.jp/en/timetable/detail/Narita-Shibuya/"
   }
  ],
  "priority": "medium",
  "sort": 10,
  "time": "",
  "title": "Limousine bus, Narita T1 → Cerulean Tower, Apr 1"
 },
 "items/b14": {
  "cat": "flights",
  "cost": 1500,
  "cur": "JPY",
  "detail": "Nick has hayashi beef pre-ordered; Kristin has no meal.",
  "done": false,
  "group": "b-fly",
  "links": [
   {
    "label": "ZIPAIR: manage booking",
    "url": "https://www.zipair.net/"
   }
  ],
  "paid": false,
  "priority": "low",
  "sort": 20,
  "time": "",
  "title": "Add Kristin's meal on ZG023"
 },
 "items/b15": {
  "cat": "other",
  "cost": 40,
  "cur": "USD",
  "detail": "",
  "done": false,
  "group": "b-fly",
  "paid": false,
  "priority": "low",
  "sort": 30,
  "time": "",
  "title": "Set up eSIMs and add Suica to your phones"
 },
 "items/b16": {
  "detail": "Around 10:30 AM. Sales open 30 days ahead (Mar 15).",
  "done": false,
  "end": "",
  "group": "b-march",
  "kind": "activity",
  "links": [
   {
    "label": "Skyliner e-ticket",
    "url": "https://www.keisei.co.jp/keisei/tetudou/skyliner/e-ticket/en/faq/"
   }
  ],
  "priority": "medium",
  "sort": 40,
  "start": "",
  "title": "Skyliner seats, Nippori → Narita, Apr 14"
 },
 "items/b17": {
  "detail": "Odawara → Kyoto, Kyoto → Okayama, Okayama → Tokyo. Seats open one month ahead; changes are free.",
  "done": false,
  "end": "",
  "group": "b-march",
  "kind": "activity",
  "links": [
   {
    "label": "smart EX",
    "url": "https://smart-ex.jp/en/lp/app/"
   }
  ],
  "priority": "high",
  "sort": 50,
  "start": "",
  "title": "Shinkansen seats: Apr 6, Apr 10, Apr 12"
 },
 "items/b18": {
  "cat": "flights",
  "cost": 2200,
  "cur": "USD",
  "detail": "Estimate including seats and outbound bags. Edit this to what you actually paid, then mark it paid.",
  "done": true,
  "end": "",
  "group": "b-now",
  "kind": "activity",
  "links": [
   {
    "label": "ZIPAIR: manage booking",
    "url": "https://www.zipair.net/"
   }
  ],
  "paid": false,
  "priority": "low",
  "sort": 5,
  "start": "",
  "title": "ZIPAIR round trip for two (booked Sep 8)"
 },
 "items/d01-01": {
  "detail": "ZG023 lands at 2:10 PM. Allow about 90 minutes.",
  "done": false,
  "end": "15:40",
  "group": "d01",
  "kind": "activity",
  "lat": null,
  "lng": null,
  "place": "Narita Airport Terminal 1",
  "priority": "high",
  "sort": 10,
  "start": "14:10",
  "title": "Land at Narita Terminal 1: immigration, bags, customs"
 },
 "items/d01-02": {
  "detail": "7-Bank ATMs in the arrivals hall take US cards.",
  "done": false,
  "end": "16:10",
  "group": "d01",
  "kind": "activity",
  "priority": "low",
  "sort": 20,
  "start": "15:40",
  "title": "Airport errands: yen, Suica, eSIM"
 },
 "items/d01-03": {
  "cat": "transit",
  "cost": 7200,
  "cur": "JPY",
  "detail": "Reserved seat, ¥3,600 each. If immigration runs long, the next bus is 5:50 PM (arrives 7:35).",
  "done": false,
  "end": "18:05",
  "group": "d01",
  "kind": "travel",
  "links": [
   {
    "label": "Reserve the bus",
    "url": "https://www.limousinebus.co.jp/en/timetable/detail/Narita-Shibuya/"
   }
  ],
  "paid": false,
  "priority": "high",
  "sort": 30,
  "start": "16:20",
  "title": "Airport Limousine bus, Terminal 1 → Cerulean Tower"
 },
 "items/d01-04": {
  "cat": "lodging",
  "cost": 680,
  "cur": "USD",
  "detail": "Shower and reset. 1 night, $680.",
  "done": false,
  "end": "18:45",
  "group": "d01",
  "kind": "activity",
  "lat": 35.6561,
  "links": [
   {
    "label": "Cerulean Tower",
    "url": "https://tokyuhotels.co.jp/en/cerulean-h/access/index.html"
   }
  ],
  "lng": 139.6989,
  "paid": false,
  "place": "Cerulean Tower Tokyu Hotel, Shibuya",
  "priority": "medium",
  "sort": 40,
  "start": "18:05",
  "title": "Check in at Cerulean Tower",
  "hotelQuery": "セルリアンタワー東急ホテル",
  "nights": 1
 },
 "items/d01-05": {
  "detail": "Watch the crossing lit up at night.",
  "done": false,
  "end": "19:15",
  "group": "d01",
  "kind": "activity",
  "lat": 35.6595,
  "lng": 139.7005,
  "place": "Shibuya Scramble Crossing",
  "priority": "low",
  "sort": 50,
  "start": "18:45",
  "title": "Walk down Sakuragaoka to Shibuya Crossing"
 },
 "items/d01-06": {
  "cat": "food",
  "cost": 8000,
  "cur": "JPY",
  "detail": "Postwar alley of six-seat bars and yakitori counters by the tracks.",
  "done": false,
  "end": "20:45",
  "group": "d01",
  "kind": "activity",
  "lat": 35.6593,
  "lng": 139.7031,
  "paid": false,
  "place": "Nonbei Yokocho, Shibuya",
  "priority": "medium",
  "sort": 60,
  "start": "19:15",
  "title": "Dinner at Nonbei Yokocho"
 },
 "items/d01-07": {
  "cat": "food",
  "cost": 6000,
  "cur": "JPY",
  "detail": "The bar near the top of Cerulean Tower. Lights out by 10:30.",
  "done": false,
  "end": "22:00",
  "group": "d01",
  "kind": "activity",
  "lat": null,
  "lng": null,
  "paid": false,
  "place": "Bellovisto, Cerulean Tower Tokyu Hotel",
  "priority": "low",
  "sort": 70,
  "start": "21:00",
  "title": "Nightcap at Bellovisto"
 },
 "items/d02-01": {
  "detail": "Gates open at sunrise, about 5:25. 10-minute taxi from Cerulean.",
  "done": false,
  "end": "06:45",
  "group": "d02",
  "kind": "activity",
  "lat": 35.6764,
  "lng": 139.6993,
  "place": "Meiji Jingu, Shibuya",
  "priority": "low",
  "sort": 10,
  "start": "05:30",
  "title": "Meiji Jingu at sunrise"
 },
 "items/d02-02": {
  "cat": "food",
  "cost": 3000,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "08:00",
  "group": "d02",
  "kind": "activity",
  "paid": false,
  "priority": "low",
  "sort": 20,
  "start": "07:00",
  "title": "Breakfast"
 },
 "items/d02-03": {
  "cat": "transit",
  "cost": 1500,
  "cur": "JPY",
  "detail": "About 10 minutes. Bags stay at the desk until 3 PM check-in.",
  "done": false,
  "end": "09:40",
  "group": "d02",
  "kind": "travel",
  "paid": false,
  "priority": "high",
  "sort": 30,
  "start": "09:15",
  "title": "Check out, taxi to Trunk, drop bags"
 },
 "items/d02-04": {
  "cat": "transit",
  "cost": 400,
  "cur": "JPY",
  "detail": "About 15 minutes on the train.",
  "done": false,
  "end": "10:10",
  "group": "d02",
  "kind": "travel",
  "paid": false,
  "priority": "low",
  "sort": 40,
  "start": "09:40",
  "title": "Ginza Line, Omotesando → Ginza"
 },
 "items/d02-05": {
  "cat": "tickets",
  "cost": 0,
  "cur": "JPY",
  "detail": "Opens 10:00. Write postcards and mail them from the store.",
  "done": false,
  "end": "12:15",
  "group": "d02",
  "kind": "activity",
  "lat": 35.6716,
  "lng": 139.7665,
  "paid": false,
  "place": "Ginza Itoya, Ginza, Tokyo",
  "priority": "medium",
  "sort": 50,
  "start": "10:15",
  "title": "Ginza Itoya"
 },
 "items/d02-06": {
  "cat": "food",
  "cost": 4000,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "13:15",
  "group": "d02",
  "kind": "activity",
  "paid": false,
  "priority": "low",
  "sort": 60,
  "start": "12:15",
  "title": "Lunch in Ginza"
 },
 "items/d02-07": {
  "cat": "tickets",
  "cost": 0,
  "cur": "JPY",
  "detail": "KITTE building at Tokyo Station. Free; open until 8 PM on Fridays.",
  "done": false,
  "end": "15:30",
  "group": "d02",
  "kind": "activity",
  "lat": 35.6794,
  "lng": 139.7648,
  "paid": false,
  "place": "Intermediatheque, KITTE Marunouchi, Tokyo",
  "priority": "medium",
  "sort": 70,
  "start": "13:30",
  "title": "Intermediatheque"
 },
 "items/d02-08": {
  "cat": "transit",
  "cost": 500,
  "cur": "JPY",
  "detail": "About 25 minutes on the train.",
  "done": false,
  "end": "16:00",
  "group": "d02",
  "kind": "travel",
  "paid": false,
  "priority": "low",
  "sort": 80,
  "start": "15:30",
  "title": "JR Yamanote Line, Tokyo → Shibuya, walk to Trunk"
 },
 "items/d02-09": {
  "cat": "lodging",
  "cost": 660,
  "cur": "USD",
  "detail": "2 nights. Estimate: rates start around $300 a night and run higher in April.",
  "done": false,
  "end": "17:15",
  "group": "d02",
  "kind": "activity",
  "lat": 35.6626,
  "links": [
   {
    "label": "Trunk (Hotel)",
    "url": "https://trunk-hotel.com"
   }
  ],
  "lng": 139.7046,
  "paid": false,
  "place": "TRUNK(HOTEL) CAT STREET, Jingumae, Tokyo",
  "priority": "medium",
  "sort": 90,
  "start": "16:00",
  "title": "Check in at Trunk, rest",
  "hotelQuery": "TRUNK(HOTEL) CAT STREET",
  "nights": 2
 },
 "items/d02-10": {
  "cat": "transit",
  "cost": 300,
  "cur": "JPY",
  "detail": "3 minutes.",
  "done": false,
  "end": "17:45",
  "group": "d02",
  "kind": "travel",
  "paid": false,
  "priority": "low",
  "sort": 100,
  "start": "17:30",
  "title": "Tokyu Toyoko Line, Shibuya → Nakameguro"
 },
 "items/d02-11": {
  "detail": "The lanterns come on after dark.",
  "done": false,
  "end": "19:30",
  "group": "d02",
  "kind": "activity",
  "lat": 35.644,
  "lng": 139.6985,
  "place": "Meguro River, Nakameguro",
  "priority": "high",
  "sort": 110,
  "start": "17:45",
  "title": "Meguro River blossoms at dusk"
 },
 "items/d02-12": {
  "cat": "food",
  "cost": 8000,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "21:00",
  "group": "d02",
  "kind": "activity",
  "paid": false,
  "priority": "medium",
  "sort": 120,
  "start": "19:30",
  "title": "Dinner in Nakameguro"
 },
 "items/d03-01": {
  "cat": "food",
  "cost": 5000,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "08:30",
  "group": "d03",
  "kind": "activity",
  "paid": false,
  "priority": "low",
  "sort": 10,
  "start": "08:00",
  "title": "Breakfast at Trunk"
 },
 "items/d03-02": {
  "cat": "transit",
  "cost": 2500,
  "cur": "JPY",
  "detail": "About 15 minutes.",
  "done": false,
  "end": "08:50",
  "group": "d03",
  "kind": "travel",
  "paid": false,
  "priority": "low",
  "sort": 20,
  "start": "08:30",
  "title": "Taxi to Azabudai Hills"
 },
 "items/d03-03": {
  "cat": "tickets",
  "cost": 9600,
  "cur": "JPY",
  "detail": "Book the first Saturday slot; opening time varies (8:30–9:00). Free lockers. Prices are dynamic, ¥3,800–4,800 each.",
  "done": false,
  "end": "12:00",
  "group": "d03",
  "kind": "activity",
  "lat": 35.6618,
  "links": [
   {
    "label": "teamLab tickets",
    "url": "https://www.teamlab.art/e/tokyo/"
   }
  ],
  "lng": 139.7437,
  "paid": false,
  "place": "teamLab Borderless, Azabudai Hills, Tokyo",
  "priority": "high",
  "sort": 30,
  "start": "09:00",
  "title": "teamLab Borderless"
 },
 "items/d03-04": {
  "cat": "food",
  "cost": 4000,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "13:15",
  "group": "d03",
  "kind": "activity",
  "paid": false,
  "priority": "low",
  "sort": 40,
  "start": "12:00",
  "title": "Lunch at Azabudai Hills"
 },
 "items/d03-05": {
  "cat": "transit",
  "cost": 500,
  "cur": "JPY",
  "detail": "About 12 minutes on the train, 15-minute walk.",
  "done": false,
  "end": "13:45",
  "group": "d03",
  "kind": "travel",
  "paid": false,
  "priority": "low",
  "sort": 50,
  "start": "13:15",
  "title": "Namboku Line to Meguro, then walk"
 },
 "items/d03-06": {
  "cat": "tickets",
  "cost": 0,
  "cur": "JPY",
  "detail": "Open 10:00–17:00, closed Mon–Tue. Free.",
  "done": false,
  "end": "15:00",
  "group": "d03",
  "kind": "activity",
  "lat": 35.6311,
  "lng": 139.7067,
  "paid": false,
  "place": "Meguro Parasitological Museum, Tokyo",
  "priority": "medium",
  "sort": 60,
  "start": "13:45",
  "title": "Meguro Parasitological Museum"
 },
 "items/d03-07": {
  "cat": "other",
  "cost": 5000,
  "cur": "JPY",
  "detail": "Trunk front desk. Should arrive by Mon Apr 5; ask the ryokan to hold them.",
  "done": false,
  "end": "16:00",
  "group": "d03",
  "kind": "activity",
  "paid": false,
  "priority": "high",
  "sort": 70,
  "start": "15:30",
  "title": "Forward big bags to the Kyoto ryokan"
 },
 "items/d03-08": {
  "detail": "",
  "done": false,
  "end": "18:00",
  "group": "d03",
  "kind": "activity",
  "priority": "low",
  "sort": 80,
  "start": "16:00",
  "title": "Rest, pack day bags for Hakone"
 },
 "items/d03-09": {
  "cat": "transit",
  "cost": 400,
  "cur": "JPY",
  "detail": "About 7 minutes.",
  "done": false,
  "end": "18:30",
  "group": "d03",
  "kind": "travel",
  "paid": false,
  "priority": "low",
  "sort": 90,
  "start": "18:15",
  "title": "JR Yamanote Line to Shinjuku"
 },
 "items/d03-10": {
  "cat": "food",
  "cost": 7000,
  "cur": "JPY",
  "detail": "Smoky yakitori stalls by the tracks.",
  "done": false,
  "end": "20:30",
  "group": "d03",
  "kind": "activity",
  "lat": 35.693,
  "lng": 139.6995,
  "paid": false,
  "place": "Omoide Yokocho, Shinjuku",
  "priority": "low",
  "sort": 100,
  "start": "18:30",
  "title": "Dinner at Omoide Yokocho"
 },
 "items/d03-11": {
  "cat": "food",
  "cost": 6000,
  "cur": "JPY",
  "detail": "Some bars charge a seat fee; look for English signs on the door.",
  "done": false,
  "end": "22:30",
  "group": "d03",
  "kind": "activity",
  "lat": 35.694,
  "lng": 139.7046,
  "paid": false,
  "place": "Golden Gai, Shinjuku",
  "priority": "low",
  "sort": 110,
  "start": "20:30",
  "title": "Golden Gai"
 },
 "items/d04-01": {
  "cat": "food",
  "cost": 3000,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "09:30",
  "group": "d04",
  "kind": "activity",
  "paid": false,
  "priority": "low",
  "sort": 10,
  "start": "08:00",
  "title": "Breakfast, Harajuku backstreets"
 },
 "items/d04-02": {
  "cat": "transit",
  "cost": 14700,
  "cur": "JPY",
  "detail": "Buy two 2-day Hakone Free Passes from Shinjuku at the Odakyu counter (estimate about ¥6,100 each; check the current price). Taxi about ¥2,500.",
  "done": false,
  "end": "10:30",
  "group": "d04",
  "kind": "travel",
  "paid": false,
  "priority": "medium",
  "sort": 20,
  "start": "10:00",
  "title": "Check out, taxi to Shinjuku Station"
 },
 "items/d04-03": {
  "cat": "transit",
  "cost": 2400,
  "cur": "JPY",
  "detail": "Reserved seats, about 85 minutes. With the Free Pass you only pay the ¥1,200 Romancecar surcharge each.",
  "done": false,
  "end": "12:25",
  "group": "d04",
  "kind": "travel",
  "links": [
   {
    "label": "e-Romancecar",
    "url": "https://www.odakyu.jp/english/?p=4039"
   }
  ],
  "paid": false,
  "priority": "high",
  "sort": 30,
  "start": "11:00",
  "title": "Romancecar, Shinjuku → Hakone-Yumoto"
 },
 "items/d04-04": {
  "cat": "food",
  "cost": 3000,
  "cur": "JPY",
  "detail": "Soba, fish cakes, onsen manju.",
  "done": false,
  "end": "13:45",
  "group": "d04",
  "kind": "activity",
  "lat": 35.2326,
  "lng": 139.106,
  "paid": false,
  "place": "Hakone-Yumoto Station",
  "priority": "low",
  "sort": 40,
  "start": "12:30",
  "title": "Lunch on Hakone-Yumoto's station street"
 },
 "items/d04-05": {
  "cat": "transit",
  "cost": 0,
  "cur": "JPY",
  "detail": "About 25 minutes. Covered by the Free Pass.",
  "done": false,
  "end": "14:40",
  "group": "d04",
  "kind": "travel",
  "paid": false,
  "priority": "high",
  "sort": 50,
  "start": "14:00",
  "title": "Bus H to Higashi Ashinoyu, 3-minute walk"
 },
 "items/d04-06": {
  "cat": "lodging",
  "cost": 116000,
  "cur": "JPY",
  "detail": "2 nights with dinner and breakfast. From about ¥28,875 per person per night, plus ¥150 bath tax each per night.",
  "done": false,
  "end": "18:00",
  "group": "d04",
  "kind": "activity",
  "lat": 35.2215,
  "links": [
   {
    "label": "Matsuzakaya Honten",
    "url": "https://kinnotake-resorts.com/matsuzakayahonten/en/access"
   }
  ],
  "lng": 139.042,
  "paid": false,
  "place": "Matsuzakaya Honten, Ashinoyu, Hakone",
  "priority": "medium",
  "sort": 60,
  "start": "15:00",
  "title": "Check in at Matsuzakaya Honten, onsen",
  "hotelQuery": "松坂屋本店 箱根",
  "nights": 2
 },
 "items/d04-07": {
  "cat": "food",
  "cost": 0,
  "cur": "JPY",
  "detail": "Dinner time is set when you check in.",
  "done": false,
  "end": "20:30",
  "group": "d04",
  "kind": "activity",
  "paid": false,
  "priority": "medium",
  "sort": 70,
  "start": "18:30",
  "title": "Kaiseki dinner"
 },
 "items/d05-01": {
  "cat": "food",
  "cost": 0,
  "cur": "JPY",
  "detail": "Look for Fuji if the morning is clear.",
  "done": false,
  "end": "08:30",
  "group": "d05",
  "kind": "activity",
  "paid": false,
  "priority": "low",
  "sort": 10,
  "start": "07:30",
  "title": "Breakfast at the inn"
 },
 "items/d05-02": {
  "cat": "transit",
  "cost": 0,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "09:05",
  "group": "d05",
  "kind": "travel",
  "paid": false,
  "priority": "low",
  "sort": 20,
  "start": "08:45",
  "title": "Bus to Moto-Hakone"
 },
 "items/d05-03": {
  "detail": "About 45 minutes uphill through cedars.",
  "done": false,
  "end": "10:15",
  "group": "d05",
  "kind": "activity",
  "lat": 35.206,
  "lng": 139.033,
  "place": "Old Tokaido stone road, Moto-Hakone",
  "priority": "medium",
  "sort": 30,
  "start": "09:10",
  "title": "Walk the Old Tokaido stone road up to Amazake-chaya"
 },
 "items/d05-04": {
  "cat": "food",
  "cost": 1000,
  "cur": "JPY",
  "detail": "Thatched Edo-era teahouse.",
  "done": false,
  "end": "10:45",
  "group": "d05",
  "kind": "activity",
  "lat": 35.2098,
  "lng": 139.0468,
  "paid": false,
  "place": "Amazake-chaya, Hakone",
  "priority": "medium",
  "sort": 40,
  "start": "10:15",
  "title": "Amazake at Amazake-chaya"
 },
 "items/d05-05": {
  "cat": "transit",
  "cost": 0,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "11:10",
  "group": "d05",
  "kind": "travel",
  "paid": false,
  "priority": "low",
  "sort": 50,
  "start": "10:45",
  "title": "Bus back down to Moto-Hakone"
 },
 "items/d05-06": {
  "detail": "Expect a short line for the torii photo.",
  "done": false,
  "end": "12:00",
  "group": "d05",
  "kind": "activity",
  "lat": 35.2047,
  "lng": 139.0254,
  "place": "Hakone Shrine",
  "priority": "medium",
  "sort": 60,
  "start": "11:15",
  "title": "Hakone Shrine and the lakeside torii"
 },
 "items/d05-07": {
  "cat": "food",
  "cost": 3500,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "13:00",
  "group": "d05",
  "kind": "activity",
  "paid": false,
  "priority": "low",
  "sort": 70,
  "start": "12:00",
  "title": "Lunch at Moto-Hakone"
 },
 "items/d05-08": {
  "cat": "tickets",
  "cost": 1000,
  "cur": "JPY",
  "detail": "About a 20-minute walk.",
  "done": false,
  "end": "13:30",
  "group": "d05",
  "kind": "activity",
  "lat": 35.1916,
  "lng": 139.0266,
  "paid": false,
  "place": "Hakone Sekisho (Checkpoint)",
  "priority": "medium",
  "sort": 80,
  "start": "13:00",
  "title": "Cedar avenue to Hakone Checkpoint"
 },
 "items/d05-09": {
  "cat": "transit",
  "cost": 0,
  "cur": "JPY",
  "detail": "Covered by the Free Pass.",
  "done": false,
  "end": "14:15",
  "group": "d05",
  "kind": "travel",
  "paid": false,
  "priority": "medium",
  "sort": 90,
  "start": "13:45",
  "title": "Sightseeing cruise, Hakone-machi → Togendai"
 },
 "items/d05-10": {
  "cat": "transit",
  "cost": 0,
  "cur": "JPY",
  "detail": "Covered by the Free Pass. Runs 9:00–16:45; check the volcanic-gas status that morning.",
  "done": false,
  "end": "14:40",
  "group": "d05",
  "kind": "travel",
  "links": [
   {
    "label": "Ropeway status",
    "url": "https://www.hakonenavi.jp/international/en/transportation/hakone-ropeway"
   }
  ],
  "paid": false,
  "priority": "medium",
  "sort": 100,
  "start": "14:20",
  "title": "Ropeway, Togendai → Owakudani"
 },
 "items/d05-11": {
  "cat": "food",
  "cost": 500,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "15:30",
  "group": "d05",
  "kind": "activity",
  "lat": 35.2443,
  "lng": 139.0195,
  "paid": false,
  "place": "Owakudani, Hakone",
  "priority": "medium",
  "sort": 110,
  "start": "14:40",
  "title": "Owakudani steam vents and black eggs"
 },
 "items/d05-12": {
  "cat": "transit",
  "cost": 0,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "16:00",
  "group": "d05",
  "kind": "travel",
  "paid": false,
  "priority": "low",
  "sort": 120,
  "start": "15:30",
  "title": "Ropeway to Sounzan, cable car, train to Chokoku-no-Mori"
 },
 "items/d05-13": {
  "cat": "tickets",
  "cost": 3600,
  "cur": "JPY",
  "detail": "Closes 17:00; last entry around 16:30.",
  "done": false,
  "end": "17:00",
  "group": "d05",
  "kind": "activity",
  "lat": 35.2448,
  "lng": 139.0513,
  "paid": false,
  "place": "Hakone Open-Air Museum",
  "priority": "low",
  "sort": 130,
  "start": "16:00",
  "title": "Hakone Open-Air Museum"
 },
 "items/d05-14": {
  "cat": "transit",
  "cost": 3000,
  "cur": "JPY",
  "detail": "About 15 minutes.",
  "done": false,
  "end": "17:25",
  "group": "d05",
  "kind": "travel",
  "paid": false,
  "priority": "low",
  "sort": 140,
  "start": "17:05",
  "title": "Taxi back to the inn"
 },
 "items/d05-15": {
  "cat": "food",
  "cost": 0,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "20:30",
  "group": "d05",
  "kind": "activity",
  "paid": false,
  "priority": "medium",
  "sort": 150,
  "start": "18:30",
  "title": "Second kaiseki dinner"
 },
 "items/d06-01": {
  "cat": "food",
  "cost": 0,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "08:30",
  "group": "d06",
  "kind": "activity",
  "paid": false,
  "priority": "low",
  "sort": 10,
  "start": "07:30",
  "title": "Breakfast and a last soak"
 },
 "items/d06-02": {
  "cat": "transit",
  "cost": 1600,
  "cur": "JPY",
  "detail": "Checkout by 11:00. The 2-day Free Pass has run out by today, so pay the bus fare (IC card works).",
  "done": false,
  "end": "11:10",
  "group": "d06",
  "kind": "travel",
  "paid": false,
  "priority": "high",
  "sort": 20,
  "start": "10:30",
  "title": "Check out, bus H to Hakone-Yumoto"
 },
 "items/d06-03": {
  "cat": "transit",
  "cost": 720,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "11:35",
  "group": "d06",
  "kind": "travel",
  "paid": false,
  "priority": "medium",
  "sort": 30,
  "start": "11:15",
  "title": "Train, Hakone-Yumoto → Odawara"
 },
 "items/d06-04": {
  "cat": "transit",
  "cost": 23000,
  "cur": "JPY",
  "detail": "About 2 hours. Buy a bento at Odawara.",
  "done": false,
  "end": "13:55",
  "group": "d06",
  "kind": "travel",
  "links": [
   {
    "label": "smart EX",
    "url": "https://smart-ex.jp/en/lp/app/"
   }
  ],
  "paid": false,
  "priority": "high",
  "sort": 40,
  "start": "11:50",
  "title": "Hikari Shinkansen, Odawara → Kyoto"
 },
 "items/d06-05": {
  "cat": "transit",
  "cost": 2000,
  "cur": "JPY",
  "detail": "About 15 minutes.",
  "done": false,
  "end": "14:30",
  "group": "d06",
  "kind": "travel",
  "paid": false,
  "priority": "low",
  "sort": 50,
  "start": "14:00",
  "title": "Taxi to the Higashiyama ryokan"
 },
 "items/d06-06": {
  "cat": "lodging",
  "cost": 800,
  "cur": "USD",
  "detail": "4 nights, estimate. Your forwarded bags should be waiting.",
  "done": false,
  "end": "16:15",
  "group": "d06",
  "kind": "activity",
  "lat": 35.0036,
  "links": [
   {
    "label": "Gion Sano",
    "url": "https://www.insidekyoto.com/kyoto-ryokan-gion-sano"
   },
   {
    "label": "Yuzuya",
    "url": "https://booking.com/hotel/jp/yuzuya-ryokan.html"
   }
  ],
  "lng": 135.778,
  "paid": false,
  "place": "Gion, Higashiyama, Kyoto",
  "priority": "medium",
  "sort": 60,
  "start": "14:30",
  "title": "Check in and rest",
  "hotelQuery": "祇園佐の",
  "nights": 4
 },
 "items/d06-07": {
  "cat": "transit",
  "cost": 600,
  "cur": "JPY",
  "detail": "About 10 minutes.",
  "done": false,
  "end": "16:40",
  "group": "d06",
  "kind": "travel",
  "paid": false,
  "priority": "low",
  "sort": 70,
  "start": "16:15",
  "title": "Keihan Line, Gion-Shijo → Fushimi-Inari"
 },
 "items/d06-08": {
  "detail": "Sunset is about 6:20 PM.",
  "done": false,
  "end": "18:45",
  "group": "d06",
  "kind": "activity",
  "lat": 34.9671,
  "lng": 135.7727,
  "place": "Fushimi Inari Taisha, Kyoto",
  "priority": "high",
  "sort": 80,
  "start": "16:45",
  "title": "Fushimi Inari: climb to Yotsutsuji for sunset"
 },
 "items/d06-09": {
  "cat": "food",
  "cost": 10000,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "21:00",
  "group": "d06",
  "kind": "activity",
  "lat": 35.0052,
  "lng": 135.7708,
  "paid": false,
  "place": "Pontocho, Kyoto",
  "priority": "low",
  "sort": 90,
  "start": "19:15",
  "title": "Dinner in Pontocho"
 },
 "items/d07-01": {
  "cat": "tickets",
  "cost": 1000,
  "cur": "JPY",
  "detail": "Opens 6:00, before the tour buses.",
  "done": false,
  "end": "07:30",
  "group": "d07",
  "kind": "activity",
  "lat": 34.9949,
  "lng": 135.785,
  "paid": false,
  "place": "Kiyomizu-dera, Kyoto",
  "priority": "high",
  "sort": 10,
  "start": "05:45",
  "title": "Kiyomizu-dera at opening, via Ninenzaka and Sannenzaka"
 },
 "items/d07-02": {
  "cat": "food",
  "cost": 3000,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "09:00",
  "group": "d07",
  "kind": "activity",
  "paid": false,
  "priority": "low",
  "sort": 20,
  "start": "07:45",
  "title": "Breakfast at the ryokan"
 },
 "items/d07-03": {
  "cat": "transit",
  "cost": 1500,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "09:40",
  "group": "d07",
  "kind": "travel",
  "paid": false,
  "priority": "low",
  "sort": 30,
  "start": "09:15",
  "title": "Taxi to Nanzen-ji"
 },
 "items/d07-04": {
  "detail": "",
  "done": false,
  "end": "10:15",
  "group": "d07",
  "kind": "activity",
  "lat": 35.0112,
  "lng": 135.7936,
  "place": "Nanzen-ji, Kyoto",
  "priority": "medium",
  "sort": 40,
  "start": "09:40",
  "title": "Nanzen-ji and its brick aqueduct"
 },
 "items/d07-05": {
  "detail": "2 km of canal and cherry trees heading north.",
  "done": false,
  "end": "11:45",
  "group": "d07",
  "kind": "activity",
  "lat": 35.0215,
  "lng": 135.7946,
  "place": "Philosopher's Path, Kyoto",
  "priority": "medium",
  "sort": 50,
  "start": "10:15",
  "title": "Philosopher's Path"
 },
 "items/d07-06": {
  "cat": "tickets",
  "cost": 1000,
  "cur": "JPY",
  "detail": "Open 8:30–17:00.",
  "done": false,
  "end": "12:45",
  "group": "d07",
  "kind": "activity",
  "lat": 35.027,
  "lng": 135.7982,
  "paid": false,
  "place": "Ginkaku-ji, Kyoto",
  "priority": "medium",
  "sort": 60,
  "start": "11:45",
  "title": "Ginkaku-ji"
 },
 "items/d07-07": {
  "cat": "food",
  "cost": 3500,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "13:45",
  "group": "d07",
  "kind": "activity",
  "paid": false,
  "priority": "low",
  "sort": 70,
  "start": "12:45",
  "title": "Lunch near Ginkaku-ji"
 },
 "items/d07-08": {
  "detail": "",
  "done": false,
  "end": "15:00",
  "group": "d07",
  "kind": "activity",
  "priority": "low",
  "sort": 80,
  "start": "14:00",
  "title": "Rest at the ryokan"
 },
 "items/d07-09": {
  "cat": "food",
  "cost": 4000,
  "cur": "JPY",
  "detail": "Most stalls close around 5 PM.",
  "done": false,
  "end": "16:30",
  "group": "d07",
  "kind": "activity",
  "lat": 35.005,
  "lng": 135.765,
  "paid": false,
  "place": "Nishiki Market, Kyoto",
  "priority": "medium",
  "sort": 90,
  "start": "15:00",
  "title": "Nishiki Market and Nishiki Tenmangu"
 },
 "items/d07-10": {
  "detail": "Golden hour. Don't chase or photograph maiko.",
  "done": false,
  "end": "18:30",
  "group": "d07",
  "kind": "activity",
  "lat": 35.0058,
  "lng": 135.7747,
  "place": "Gion Shirakawa, Kyoto",
  "priority": "low",
  "sort": 100,
  "start": "17:15",
  "title": "Gion: Shirakawa canal and Hanamikoji"
 },
 "items/d07-11": {
  "cat": "food",
  "cost": 10000,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "20:30",
  "group": "d07",
  "kind": "activity",
  "paid": false,
  "priority": "low",
  "sort": 110,
  "start": "18:30",
  "title": "Dinner in Gion"
 },
 "items/d08-01": {
  "cat": "transit",
  "cost": 5000,
  "cur": "JPY",
  "detail": "About 30 minutes from Higashiyama.",
  "done": false,
  "end": "07:00",
  "group": "d08",
  "kind": "travel",
  "paid": false,
  "priority": "low",
  "sort": 10,
  "start": "06:30",
  "title": "Taxi to Arashiyama"
 },
 "items/d08-02": {
  "detail": "",
  "done": false,
  "end": "08:15",
  "group": "d08",
  "kind": "activity",
  "lat": 35.017,
  "lng": 135.6717,
  "place": "Arashiyama Bamboo Grove, Kyoto",
  "priority": "high",
  "sort": 20,
  "start": "07:00",
  "title": "Arashiyama bamboo grove at first light"
 },
 "items/d08-03": {
  "cat": "tickets",
  "cost": 1000,
  "cur": "JPY",
  "detail": "Opens 8:30.",
  "done": false,
  "end": "09:30",
  "group": "d08",
  "kind": "activity",
  "lat": 35.0158,
  "lng": 135.6738,
  "paid": false,
  "place": "Tenryu-ji, Kyoto",
  "priority": "medium",
  "sort": 30,
  "start": "08:30",
  "title": "Tenryu-ji garden"
 },
 "items/d08-04": {
  "cat": "transit",
  "cost": 1500,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "09:45",
  "group": "d08",
  "kind": "travel",
  "paid": false,
  "priority": "low",
  "sort": 40,
  "start": "09:30",
  "title": "Taxi to Otagi Nenbutsu-ji"
 },
 "items/d08-05": {
  "cat": "tickets",
  "cost": 600,
  "cur": "JPY",
  "detail": "1,200 moss-covered stone rakan.",
  "done": false,
  "end": "10:45",
  "group": "d08",
  "kind": "activity",
  "lat": 35.0291,
  "lng": 135.6645,
  "paid": false,
  "place": "Otagi Nenbutsu-ji, Kyoto",
  "priority": "medium",
  "sort": 50,
  "start": "09:45",
  "title": "Otagi Nenbutsu-ji"
 },
 "items/d08-06": {
  "detail": "Edo-era thatched townhouses.",
  "done": false,
  "end": "11:30",
  "group": "d08",
  "kind": "activity",
  "lat": 35.0264,
  "lng": 135.6682,
  "place": "Saga-Toriimoto Preserved Street, Kyoto",
  "priority": "low",
  "sort": 60,
  "start": "10:45",
  "title": "Walk down Saga-Toriimoto preserved street"
 },
 "items/d08-07": {
  "cat": "food",
  "cost": 4000,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "13:00",
  "group": "d08",
  "kind": "activity",
  "paid": false,
  "priority": "low",
  "sort": 70,
  "start": "11:45",
  "title": "Lunch in Arashiyama"
 },
 "items/d08-08": {
  "cat": "transit",
  "cost": 500,
  "cur": "JPY",
  "detail": "About 20 minutes.",
  "done": false,
  "end": "13:40",
  "group": "d08",
  "kind": "travel",
  "paid": false,
  "priority": "low",
  "sort": 80,
  "start": "13:15",
  "title": "Randen tram, Arashiyama → Omuro-Ninnaji"
 },
 "items/d08-09": {
  "cat": "tickets",
  "cost": 1600,
  "cur": "JPY",
  "detail": "The city's late bloomers. Open 9:00–17:00.",
  "done": false,
  "end": "15:15",
  "group": "d08",
  "kind": "activity",
  "lat": 35.031,
  "lng": 135.7137,
  "paid": false,
  "place": "Ninna-ji, Kyoto",
  "priority": "medium",
  "sort": 90,
  "start": "13:45",
  "title": "Ninna-ji and the Omuro cherries"
 },
 "items/d08-10": {
  "cat": "tickets",
  "cost": 1000,
  "cur": "JPY",
  "detail": "10 minutes by taxi; closes 17:00.",
  "done": false,
  "end": "16:45",
  "group": "d08",
  "kind": "activity",
  "lat": 35.0394,
  "lng": 135.7292,
  "paid": false,
  "place": "Kinkaku-ji, Kyoto",
  "priority": "medium",
  "sort": 100,
  "start": "15:30",
  "title": "Kinkaku-ji"
 },
 "items/d08-11": {
  "cat": "transit",
  "cost": 3500,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "17:30",
  "group": "d08",
  "kind": "travel",
  "paid": false,
  "priority": "low",
  "sort": 110,
  "start": "17:00",
  "title": "Taxi back to the ryokan"
 },
 "items/d08-12": {
  "cat": "food",
  "cost": 8000,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "20:30",
  "group": "d08",
  "kind": "activity",
  "paid": false,
  "priority": "low",
  "sort": 120,
  "start": "19:00",
  "title": "Dinner"
 },
 "items/d09-01": {
  "cat": "food",
  "cost": 3000,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "08:15",
  "group": "d09",
  "kind": "activity",
  "paid": false,
  "priority": "low",
  "sort": 10,
  "start": "07:30",
  "title": "Breakfast"
 },
 "items/d09-02": {
  "cat": "transit",
  "cost": 2600,
  "cur": "JPY",
  "detail": "About 35 minutes; reserved seats.",
  "done": false,
  "end": "09:15",
  "group": "d09",
  "kind": "travel",
  "paid": false,
  "priority": "medium",
  "sort": 20,
  "start": "08:30",
  "title": "Kintetsu Limited Express, Kyoto → Kintetsu-Nara"
 },
 "items/d09-03": {
  "detail": "",
  "done": false,
  "end": "10:00",
  "group": "d09",
  "kind": "activity",
  "lat": 34.6831,
  "lng": 135.8317,
  "place": "Kofuku-ji, Nara",
  "priority": "low",
  "sort": 30,
  "start": "09:15",
  "title": "Kofuku-ji and the deer park"
 },
 "items/d09-04": {
  "cat": "tickets",
  "cost": 1600,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "11:30",
  "group": "d09",
  "kind": "activity",
  "lat": 34.689,
  "lng": 135.8398,
  "paid": false,
  "place": "Todai-ji, Nara",
  "priority": "high",
  "sort": 40,
  "start": "10:00",
  "title": "Todai-ji Great Buddha Hall"
 },
 "items/d09-05": {
  "detail": "",
  "done": false,
  "end": "12:15",
  "group": "d09",
  "kind": "activity",
  "lat": 34.6892,
  "lng": 135.8438,
  "place": "Nigatsu-do, Todai-ji, Nara",
  "priority": "low",
  "sort": 50,
  "start": "11:30",
  "title": "Nigatsu-do balcony view"
 },
 "items/d09-06": {
  "cat": "food",
  "cost": 3500,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "13:30",
  "group": "d09",
  "kind": "activity",
  "paid": false,
  "priority": "low",
  "sort": 60,
  "start": "12:15",
  "title": "Lunch"
 },
 "items/d09-07": {
  "cat": "tickets",
  "cost": 1000,
  "cur": "JPY",
  "detail": "3,000 stone and bronze lanterns.",
  "done": false,
  "end": "15:00",
  "group": "d09",
  "kind": "activity",
  "lat": 34.6813,
  "lng": 135.8483,
  "paid": false,
  "place": "Kasuga Taisha, Nara",
  "priority": "medium",
  "sort": 70,
  "start": "13:30",
  "title": "Kasuga Taisha lantern paths"
 },
 "items/d09-08": {
  "detail": "",
  "done": false,
  "end": "16:30",
  "group": "d09",
  "kind": "activity",
  "lat": 34.6776,
  "lng": 135.8298,
  "place": "Naramachi, Nara",
  "priority": "low",
  "sort": 80,
  "start": "15:00",
  "title": "Naramachi merchant lanes"
 },
 "items/d09-09": {
  "cat": "transit",
  "cost": 1600,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "17:30",
  "group": "d09",
  "kind": "travel",
  "paid": false,
  "priority": "low",
  "sort": 90,
  "start": "16:45",
  "title": "Kintetsu back to Kyoto"
 },
 "items/d09-10": {
  "cat": "other",
  "cost": 5000,
  "cur": "JPY",
  "detail": "Should arrive by Mon Apr 12.",
  "done": false,
  "end": "18:15",
  "group": "d09",
  "kind": "activity",
  "paid": false,
  "priority": "high",
  "sort": 100,
  "start": "17:45",
  "title": "Forward big bags to east Tokyo, pack day bags"
 },
 "items/d09-11": {
  "cat": "food",
  "cost": 40000,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "20:30",
  "group": "d09",
  "kind": "activity",
  "paid": false,
  "priority": "medium",
  "sort": 110,
  "start": "18:30",
  "title": "Farewell kaiseki"
 },
 "items/d10-01": {
  "cat": "food",
  "cost": 3000,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "07:45",
  "group": "d10",
  "kind": "activity",
  "paid": false,
  "priority": "low",
  "sort": 10,
  "start": "07:00",
  "title": "Breakfast, check out"
 },
 "items/d10-02": {
  "cat": "transit",
  "cost": 2000,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "08:10",
  "group": "d10",
  "kind": "travel",
  "paid": false,
  "priority": "low",
  "sort": 20,
  "start": "07:45",
  "title": "Taxi to Kyoto Station"
 },
 "items/d10-03": {
  "cat": "transit",
  "cost": 15600,
  "cur": "JPY",
  "detail": "About 65 minutes; any Nozomi around 8:10 works.",
  "done": false,
  "end": "09:20",
  "group": "d10",
  "kind": "travel",
  "links": [
   {
    "label": "smart EX",
    "url": "https://smart-ex.jp/en/lp/app/"
   }
  ],
  "paid": false,
  "priority": "high",
  "sort": 30,
  "start": "08:15",
  "title": "Nozomi Shinkansen, Kyoto → Okayama"
 },
 "items/d10-04": {
  "cat": "transit",
  "cost": 1200,
  "cur": "JPY",
  "detail": "Same-platform transfer at Chayamachi.",
  "done": false,
  "end": "10:36",
  "group": "d10",
  "kind": "travel",
  "links": [
   {
    "label": "Uno Line timetable",
    "url": "https://unoportinn.com/jr-train-fromto-uno-tofrom-okayama/"
   }
  ],
  "paid": false,
  "priority": "high",
  "sort": 40,
  "start": "09:33",
  "title": "Marine Liner to Chayamachi, change for Uno"
 },
 "items/d10-05": {
  "cat": "transit",
  "cost": 740,
  "cur": "JPY",
  "detail": "¥370 each, no reservations. Backup ferry at 12:15.",
  "done": false,
  "end": "11:20",
  "group": "d10",
  "kind": "travel",
  "links": [
   {
    "label": "Ferry timetable",
    "url": "https://shikokukisen.com/uno-miyanoura/"
   }
  ],
  "paid": false,
  "priority": "high",
  "sort": 50,
  "start": "11:00",
  "title": "Ferry, Uno → Miyanoura"
 },
 "items/d10-06": {
  "cat": "lodging",
  "cost": 500,
  "cur": "USD",
  "detail": "2 nights at the $250-a-night target. Roka runs much higher: listed from about ¥99,000 a night.",
  "done": false,
  "end": "12:00",
  "group": "d10",
  "kind": "activity",
  "lat": 34.4615,
  "links": [
   {
    "label": "Naoshima Ryokan Roka",
    "url": "https://roka.voyage/en/"
   }
  ],
  "lng": 133.9745,
  "paid": false,
  "place": "Miyanoura Port, Naoshima",
  "priority": "medium",
  "sort": 60,
  "start": "11:20",
  "title": "Drop bags at your Naoshima stay, rent e-bikes",
  "hotelQuery": "直島旅館 ろ霞",
  "nights": 2
 },
 "items/d10-07": {
  "cat": "food",
  "cost": 3000,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "13:00",
  "group": "d10",
  "kind": "activity",
  "paid": false,
  "priority": "low",
  "sort": 70,
  "start": "12:00",
  "title": "Lunch near Miyanoura port"
 },
 "items/d10-08": {
  "cat": "transit",
  "cost": 6000,
  "cur": "JPY",
  "detail": "About 25 minutes. E-bikes for two for both days, about ¥1,500 each per day.",
  "done": false,
  "end": "13:45",
  "group": "d10",
  "kind": "travel",
  "paid": false,
  "priority": "low",
  "sort": 80,
  "start": "13:15",
  "title": "Ride to the Chichu ticket center"
 },
 "items/d10-09": {
  "cat": "tickets",
  "cost": 5400,
  "cur": "JPY",
  "detail": "Timed ticket; void if you're 30+ minutes late. ¥2,700 each online on weekends.",
  "done": false,
  "end": "15:30",
  "group": "d10",
  "kind": "activity",
  "lat": 34.45,
  "links": [
   {
    "label": "Chichu tickets",
    "url": "https://www.e-tix.jp/chichu/en/"
   }
  ],
  "lng": 133.986,
  "paid": false,
  "place": "Chichu Art Museum, Naoshima",
  "priority": "high",
  "sort": 90,
  "start": "14:00",
  "title": "Chichu Art Museum"
 },
 "items/d10-10": {
  "cat": "tickets",
  "cost": 2100,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "16:40",
  "group": "d10",
  "kind": "activity",
  "lat": 34.4478,
  "lng": 133.9892,
  "paid": false,
  "place": "Lee Ufan Museum, Naoshima",
  "priority": "medium",
  "sort": 100,
  "start": "15:40",
  "title": "Lee Ufan Museum"
 },
 "items/d10-11": {
  "cat": "tickets",
  "cost": 2600,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "18:10",
  "group": "d10",
  "kind": "activity",
  "lat": 34.4467,
  "lng": 133.9932,
  "paid": false,
  "place": "Benesse House Museum, Naoshima",
  "priority": "medium",
  "sort": 110,
  "start": "16:50",
  "title": "Benesse House Museum"
 },
 "items/d10-12": {
  "detail": "Sunset is about 6:35 PM.",
  "done": false,
  "end": "18:45",
  "group": "d10",
  "kind": "activity",
  "lat": 34.444,
  "lng": 133.996,
  "place": "Yellow Pumpkin, Naoshima",
  "priority": "medium",
  "sort": 120,
  "start": "18:15",
  "title": "Yellow pumpkin at sunset"
 },
 "items/d10-13": {
  "cat": "food",
  "cost": 8000,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "20:00",
  "group": "d10",
  "kind": "activity",
  "paid": false,
  "priority": "low",
  "sort": 130,
  "start": "19:00",
  "title": "Dinner"
 },
 "items/d10-14": {
  "cat": "tickets",
  "cost": 1320,
  "cur": "JPY",
  "detail": "Check the last entry time.",
  "done": false,
  "end": "21:00",
  "group": "d10",
  "kind": "activity",
  "lat": 34.4605,
  "lng": 133.975,
  "paid": false,
  "place": "Naoshima Bath I Love Yu",
  "priority": "low",
  "sort": 140,
  "start": "20:15",
  "title": "Naoshima Bath I♥湯"
 },
 "items/d11-01": {
  "cat": "food",
  "cost": 3000,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "09:00",
  "group": "d11",
  "kind": "activity",
  "paid": false,
  "priority": "low",
  "sort": 10,
  "start": "08:00",
  "title": "Breakfast"
 },
 "items/d11-02": {
  "detail": "",
  "done": false,
  "end": "09:50",
  "group": "d11",
  "kind": "travel",
  "priority": "low",
  "sort": 20,
  "start": "09:30",
  "title": "Ride to Honmura"
 },
 "items/d11-03": {
  "cat": "tickets",
  "cost": 3000,
  "cur": "JPY",
  "detail": "Opens 10:00. Book a Minamidera slot around 10:15.",
  "done": false,
  "end": "11:35",
  "group": "d11",
  "kind": "activity",
  "lat": 34.4585,
  "links": [
   {
    "label": "Minamidera tickets",
    "url": "https://benesse-artsite.jp/en/general-information.html"
   }
  ],
  "lng": 133.999,
  "paid": false,
  "place": "Art House Project, Honmura, Naoshima",
  "priority": "high",
  "sort": 30,
  "start": "10:00",
  "title": "Honmura Art House Project, with Minamidera"
 },
 "items/d11-04": {
  "detail": "Park the bikes; the boat is cash only, ¥820.",
  "done": false,
  "end": "11:55",
  "group": "d11",
  "kind": "travel",
  "priority": "high",
  "sort": 40,
  "start": "11:35",
  "title": "Ride to Miyanoura port"
 },
 "items/d11-05": {
  "cat": "transit",
  "cost": 1640,
  "cur": "JPY",
  "detail": "No reservations; first come, first served.",
  "done": false,
  "end": "12:32",
  "group": "d11",
  "kind": "travel",
  "links": [
   {
    "label": "Boat timetable",
    "url": "https://shikokukisen.com/miyanoura-ieura-inujima/"
   }
  ],
  "paid": false,
  "priority": "high",
  "sort": 50,
  "start": "12:10",
  "title": "Boat, Miyanoura → Ieura (Teshima)"
 },
 "items/d11-06": {
  "cat": "transit",
  "cost": 4000,
  "cur": "JPY",
  "detail": "About 20 minutes.",
  "done": false,
  "end": "13:00",
  "group": "d11",
  "kind": "travel",
  "paid": false,
  "priority": "medium",
  "sort": 60,
  "start": "12:35",
  "title": "Rent e-bikes at Ieura, ride toward Karato"
 },
 "items/d11-07": {
  "cat": "food",
  "cost": 3500,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "13:45",
  "group": "d11",
  "kind": "activity",
  "paid": false,
  "priority": "low",
  "sort": 70,
  "start": "13:00",
  "title": "Lunch near Karato"
 },
 "items/d11-08": {
  "cat": "tickets",
  "cost": 3200,
  "cur": "JPY",
  "detail": "Timed ticket.",
  "done": false,
  "end": "15:00",
  "group": "d11",
  "kind": "activity",
  "lat": 34.4879,
  "links": [
   {
    "label": "Teshima tickets",
    "url": "https://benesse-artsite.jp/en/general-information.html"
   }
  ],
  "lng": 134.0925,
  "paid": false,
  "place": "Teshima Art Museum",
  "priority": "high",
  "sort": 80,
  "start": "14:00",
  "title": "Teshima Art Museum"
 },
 "items/d11-09": {
  "cat": "tickets",
  "cost": 1600,
  "cur": "JPY",
  "detail": "Record your heartbeats together.",
  "done": false,
  "end": "15:45",
  "group": "d11",
  "kind": "activity",
  "lat": 34.4935,
  "lng": 134.1015,
  "paid": false,
  "place": "Les Archives du Coeur, Teshima",
  "priority": "medium",
  "sort": 90,
  "start": "15:10",
  "title": "Les Archives du Cœur"
 },
 "items/d11-10": {
  "detail": "The 4:17 boat is the last one back to Naoshima.",
  "done": false,
  "end": "16:10",
  "group": "d11",
  "kind": "travel",
  "priority": "high",
  "sort": 100,
  "start": "15:45",
  "title": "Ride back to Ieura, return bikes"
 },
 "items/d11-11": {
  "cat": "transit",
  "cost": 1640,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "16:39",
  "group": "d11",
  "kind": "travel",
  "links": [
   {
    "label": "Boat timetable",
    "url": "https://shikokukisen.com/miyanoura-ieura-inujima/"
   }
  ],
  "paid": false,
  "priority": "high",
  "sort": 110,
  "start": "16:17",
  "title": "Boat, Ieura → Miyanoura"
 },
 "items/d11-12": {
  "detail": "",
  "done": false,
  "end": "19:00",
  "group": "d11",
  "kind": "activity",
  "priority": "low",
  "sort": 120,
  "start": "17:00",
  "title": "Rest"
 },
 "items/d11-13": {
  "cat": "food",
  "cost": 8000,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "20:30",
  "group": "d11",
  "kind": "activity",
  "paid": false,
  "priority": "low",
  "sort": 130,
  "start": "19:00",
  "title": "Dinner"
 },
 "items/d12-01": {
  "cat": "food",
  "cost": 3000,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "08:30",
  "group": "d12",
  "kind": "activity",
  "paid": false,
  "priority": "low",
  "sort": 10,
  "start": "07:15",
  "title": "Breakfast, check out"
 },
 "items/d12-02": {
  "cat": "transit",
  "cost": 740,
  "cur": "JPY",
  "detail": "Backup ferry at 9:52.",
  "done": false,
  "end": "09:12",
  "group": "d12",
  "kind": "travel",
  "links": [
   {
    "label": "Ferry timetable",
    "url": "https://shikokukisen.com/uno-miyanoura/"
   }
  ],
  "paid": false,
  "priority": "high",
  "sort": 20,
  "start": "08:52",
  "title": "Ferry, Miyanoura → Uno"
 },
 "items/d12-03": {
  "cat": "transit",
  "cost": 1200,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "10:17",
  "group": "d12",
  "kind": "travel",
  "links": [
   {
    "label": "Uno Line timetable",
    "url": "https://unoportinn.com/jr-train-fromto-uno-tofrom-okayama/"
   }
  ],
  "paid": false,
  "priority": "high",
  "sort": 30,
  "start": "09:35",
  "title": "Train, Uno → Okayama (change at Chayamachi)"
 },
 "items/d12-04": {
  "cat": "transit",
  "cost": 35000,
  "cur": "JPY",
  "detail": "About 3 h 20 min. Any Nozomi around 10:30 works.",
  "done": false,
  "end": "13:55",
  "group": "d12",
  "kind": "travel",
  "links": [
   {
    "label": "smart EX",
    "url": "https://smart-ex.jp/en/lp/app/"
   }
  ],
  "paid": false,
  "priority": "high",
  "sort": 40,
  "start": "10:35",
  "title": "Nozomi Shinkansen, Okayama → Tokyo"
 },
 "items/d12-05": {
  "cat": "transit",
  "cost": 400,
  "cur": "JPY",
  "detail": "Yamanote or Keihin-Tohoku Line, about 15 minutes.",
  "done": false,
  "end": "14:25",
  "group": "d12",
  "kind": "travel",
  "paid": false,
  "priority": "low",
  "sort": 50,
  "start": "14:05",
  "title": "JR to Nippori"
 },
 "items/d12-06": {
  "cat": "lodging",
  "cost": 260,
  "cur": "USD",
  "detail": "2 nights, estimate. Your bags from Kyoto should be there.",
  "done": false,
  "end": "16:15",
  "group": "d12",
  "kind": "activity",
  "lat": 35.721,
  "links": [
   {
    "label": "Ryokan Sawanoya",
    "url": "http://www.sawanoya.com/"
   }
  ],
  "lng": 139.7649,
  "paid": false,
  "place": "Ryokan Sawanoya, Yanaka, Tokyo",
  "priority": "high",
  "sort": 60,
  "start": "14:45",
  "title": "Check in, east Tokyo",
  "hotelQuery": "澤の屋",
  "nights": 2
 },
 "items/d12-07": {
  "detail": "Sunset is about 6:05 PM.",
  "done": false,
  "end": "18:10",
  "group": "d12",
  "kind": "activity",
  "lat": 35.7275,
  "lng": 139.7658,
  "place": "Yanaka Ginza, Tokyo",
  "priority": "medium",
  "sort": 70,
  "start": "16:30",
  "title": "Yanaka Ginza and the Yuyake Dandan sunset steps"
 },
 "items/d12-08": {
  "cat": "food",
  "cost": 7000,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "20:00",
  "group": "d12",
  "kind": "activity",
  "paid": false,
  "priority": "low",
  "sort": 80,
  "start": "18:30",
  "title": "Dinner in Yanaka or Nezu"
 },
 "items/d12-09": {
  "cat": "food",
  "cost": 5000,
  "cur": "JPY",
  "detail": "Kuramae; about 20 minutes by taxi from Yanaka.",
  "done": false,
  "end": "22:00",
  "group": "d12",
  "kind": "activity",
  "lat": 35.705,
  "lng": 139.791,
  "paid": false,
  "place": "Nui. Hostel & Bar Lounge, Kuramae, Tokyo",
  "priority": "low",
  "sort": 90,
  "start": "20:30",
  "title": "Drinks at Nui.'s bar lounge"
 },
 "items/d13-01": {
  "cat": "food",
  "cost": 2500,
  "cur": "JPY",
  "detail": "1930s kissaten; check its opening time.",
  "done": false,
  "end": "09:15",
  "group": "d13",
  "kind": "activity",
  "lat": 35.7187,
  "lng": 139.7707,
  "paid": false,
  "place": "Kayaba Coffee, Yanaka, Tokyo",
  "priority": "medium",
  "sort": 10,
  "start": "08:30",
  "title": "Breakfast at Kayaba Coffee"
 },
 "items/d13-02": {
  "cat": "tickets",
  "cost": 1000,
  "cur": "JPY",
  "detail": "Open 9:30–16:30; closed Mondays and Thursdays.",
  "done": false,
  "end": "10:30",
  "group": "d13",
  "kind": "activity",
  "lat": 35.7252,
  "lng": 139.7688,
  "paid": false,
  "place": "Asakura Museum of Sculpture, Tokyo",
  "priority": "medium",
  "sort": 20,
  "start": "09:30",
  "title": "Asakura Museum of Sculpture"
 },
 "items/d13-03": {
  "detail": "",
  "done": false,
  "end": "11:30",
  "group": "d13",
  "kind": "activity",
  "lat": 35.7225,
  "lng": 139.7715,
  "place": "Yanaka Cemetery, Tokyo",
  "priority": "low",
  "sort": 30,
  "start": "10:30",
  "title": "Yanaka Cemetery"
 },
 "items/d13-04": {
  "detail": "",
  "done": false,
  "end": "12:30",
  "group": "d13",
  "kind": "activity",
  "lat": 35.7202,
  "lng": 139.7607,
  "place": "Nezu Shrine, Tokyo",
  "priority": "low",
  "sort": 40,
  "start": "11:45",
  "title": "Nezu Shrine"
 },
 "items/d13-05": {
  "cat": "food",
  "cost": 3000,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "13:30",
  "group": "d13",
  "kind": "activity",
  "paid": false,
  "priority": "low",
  "sort": 50,
  "start": "12:30",
  "title": "Lunch in Nezu"
 },
 "items/d13-06": {
  "cat": "transit",
  "cost": 2000,
  "cur": "JPY",
  "detail": "About 15 minutes.",
  "done": false,
  "end": "14:15",
  "group": "d13",
  "kind": "travel",
  "paid": false,
  "priority": "low",
  "sort": 60,
  "start": "13:45",
  "title": "Taxi to Kuramae"
 },
 "items/d13-07": {
  "cat": "other",
  "cost": 6000,
  "cur": "JPY",
  "detail": "Open from noon on Tuesdays. The Inkstand may only open on weekends; check first.",
  "done": false,
  "end": "15:45",
  "group": "d13",
  "kind": "activity",
  "lat": 35.704,
  "lng": 139.792,
  "paid": false,
  "place": "Kakimori, Kuramae, Tokyo",
  "priority": "medium",
  "sort": 70,
  "start": "14:15",
  "title": "Kakimori: build a custom notebook"
 },
 "items/d13-08": {
  "detail": "Most shops close around 5 PM.",
  "done": false,
  "end": "17:00",
  "group": "d13",
  "kind": "activity",
  "lat": 35.7135,
  "lng": 139.788,
  "place": "Kappabashi Dougu Street, Tokyo",
  "priority": "medium",
  "sort": 80,
  "start": "16:00",
  "title": "Kappabashi kitchenware street"
 },
 "items/d13-09": {
  "detail": "The main hall closes at 5; the grounds stay open and lit.",
  "done": false,
  "end": "18:30",
  "group": "d13",
  "kind": "activity",
  "lat": 35.7148,
  "lng": 139.7967,
  "place": "Senso-ji, Asakusa, Tokyo",
  "priority": "medium",
  "sort": 90,
  "start": "17:15",
  "title": "Senso-ji at dusk"
 },
 "items/d13-10": {
  "cat": "food",
  "cost": 10000,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "20:00",
  "group": "d13",
  "kind": "activity",
  "paid": false,
  "priority": "medium",
  "sort": 100,
  "start": "18:30",
  "title": "Farewell dinner in Asakusa"
 },
 "items/d13-11": {
  "detail": "Carry-ons within the 8 kg on your booking; checked bags up to 30 kg.",
  "done": false,
  "end": "22:00",
  "group": "d13",
  "kind": "activity",
  "priority": "high",
  "sort": 110,
  "start": "21:00",
  "title": "Pack and weigh bags"
 },
 "items/d14-01": {
  "cat": "food",
  "cost": 2500,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "09:00",
  "group": "d14",
  "kind": "activity",
  "paid": false,
  "priority": "low",
  "sort": 10,
  "start": "08:00",
  "title": "Breakfast"
 },
 "items/d14-02": {
  "detail": "",
  "done": false,
  "end": "10:15",
  "group": "d14",
  "kind": "travel",
  "priority": "medium",
  "sort": 20,
  "start": "09:45",
  "title": "Check out, head to Nippori Station"
 },
 "items/d14-03": {
  "cat": "transit",
  "cost": 4620,
  "cur": "JPY",
  "detail": "About 40 minutes. E-ticket ¥2,310 each.",
  "done": false,
  "end": "11:10",
  "group": "d14",
  "kind": "travel",
  "links": [
   {
    "label": "Skyliner e-ticket",
    "url": "https://www.keisei.co.jp/keisei/tetudou/skyliner/e-ticket/en/faq/"
   }
  ],
  "paid": false,
  "priority": "high",
  "sort": 30,
  "start": "10:30",
  "title": "Skyliner, Nippori → Narita Airport Terminal 1"
 },
 "items/d14-04": {
  "detail": "Counter closes at 1:35 PM.",
  "done": false,
  "end": "12:00",
  "group": "d14",
  "kind": "activity",
  "lat": null,
  "links": [
   {
    "label": "ZIPAIR check-in info",
    "url": "https://www.zipair.net/en/about"
   }
  ],
  "lng": null,
  "place": "Narita Airport Terminal 1",
  "priority": "high",
  "sort": 40,
  "start": "11:15",
  "title": "ZIPAIR check-in and bag drop"
 },
 "items/d14-05": {
  "cat": "food",
  "cost": 4000,
  "cur": "JPY",
  "detail": "",
  "done": false,
  "end": "14:00",
  "group": "d14",
  "kind": "activity",
  "paid": false,
  "priority": "low",
  "sort": 50,
  "start": "12:00",
  "title": "Security, lunch airside"
 },
 "items/d14-06": {
  "detail": "Lands at LAX at 8:25 AM the same day.",
  "done": false,
  "end": "",
  "group": "d14",
  "kind": "travel",
  "priority": "high",
  "sort": 60,
  "start": "14:35",
  "title": "ZG024 departs"
 },
 "settings/budget": {
  "cats": {
   "flights": 2200,
   "food": 1400,
   "lodging": 3900,
   "other": 200,
   "tickets": 600,
   "transit": 1000
  },
  "rate": 155,
  "useLive": true
 }
};
